"""Benchmark: nano-astar vs networkx A* on random 30%-obstacle grids.

Fairness rules:
  * identical grids, identical adjacency (8-connected, sqrt(2) diagonals,
    no corner cutting), identical (admissible octile) heuristic for both sides;
  * networkx gets the fast vectorized graph construction (build time is
    reported separately AND included in the "incl. build" column);
  * both sides are warmed up before timing; medians are reported;
  * costs are cross-checked so a faster-but-wrong result cannot hide.

Run:  python tests/bench_vs_networkx.py     (writes BENCH.md at repo root)
"""

from __future__ import annotations

import math
import platform
import statistics
import sys
import time
from pathlib import Path

import networkx as nx
import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from gridutil import nx_heuristic  # noqa: E402

from nano_astar import _core, astar  # noqa: E402

SQRT2 = math.sqrt(2.0)
REPO_ROOT = Path(__file__).resolve().parent.parent

SIZES = [100, 500, 1000]
DENSITY = 0.30
# (nx search reps, ours reps) per size — nx gets slow quickly, keep it honest
# but bounded.
REPS = {100: (5, 50), 500: (3, 30), 1000: (2, 20)}


def make_solvable_grid(size: int) -> tuple[np.ndarray, tuple, tuple, int]:
    """30%-obstacle grid with a guaranteed long path; returns grid, endpoints
    (opposite corners carved free) and the seed used."""
    seed = 0
    while True:
        rng = np.random.default_rng(seed)
        grid = (rng.random((size, size)) < DENSITY).astype(np.uint8)
        start, goal = (0, 0), (size - 1, size - 1)
        grid[start] = 0
        grid[goal] = 0
        if astar(grid, start, goal) is not None:
            return grid, start, goal, seed
        seed += 1


def build_nx_graph_fast(grid: np.ndarray) -> nx.Graph:
    """Vectorized 8-connected graph construction (same rules as the engine).
    No per-cell Python loops over the grid — edges are generated by numpy
    masking — so networkx is not handicapped by a slow graph build."""
    rows, cols = grid.shape
    free = grid == 0
    R, C = np.mgrid[0:rows, 0:cols]
    triples = []

    def emit(ra, ca, rb, cb, weight, mask):
        idx = np.argwhere(mask)
        triples.extend(
            (u, v, weight) for u, v in zip(
                zip(ra[mask].tolist(), ca[mask].tolist()),
                zip(rb[mask].tolist(), cb[mask].tolist()),
            )
        )

    # orthogonal right / down
    emit(R[:, :-1], C[:, :-1], R[:, 1:], C[:, 1:], 1.0,
         free[:, :-1] & free[:, 1:])
    emit(R[:-1, :], C[:-1, :], R[1:, :], C[1:, :], 1.0,
         free[:-1, :] & free[1:, :])
    # diagonals, no corner cutting
    for dr, dc in ((1, 1), (1, -1)):
        if dc == 1:
            ra, ca = R[:-1, :-1], C[:-1, :-1]
            rb, cb = R[1:, 1:], C[1:, 1:]
        else:
            ra, ca = R[:-1, 1:], C[:-1, 1:]
            rb, cb = R[1:, :-1], C[1:, :-1]
        emit(ra, ca, rb, cb, SQRT2,
             free[ra, ca] & free[rb, cb] & free[ra, cb] & free[rb, ca])

    G = nx.Graph()
    G.add_nodes_from(map(tuple, np.argwhere(free).tolist()))
    G.add_weighted_edges_from(triples)
    return G


def bench(fn, reps: int) -> float:
    """Median wall time in milliseconds over `reps` runs."""
    times = []
    for _ in range(reps):
        t0 = time.perf_counter()
        fn()
        times.append((time.perf_counter() - t0) * 1e3)
    return statistics.median(times)


def main() -> None:
    rows_out = []
    for size in SIZES:
        grid, start, goal, seed = make_solvable_grid(size)
        nx_reps, our_reps = REPS[size]

        # --- networkx: build once, then time search-only on the warm graph
        t0 = time.perf_counter()
        G = build_nx_graph_fast(grid)
        nx_build_ms = (time.perf_counter() - t0) * 1e3
        h = nx_heuristic(True)

        def nx_search():
            return nx.astar_path(G, start, goal, heuristic=h, weight="weight")

        nx_path = nx_search()  # warmup + reference cost
        nx_cost = sum(G[u][v]["weight"] for u, v in zip(nx_path[:-1],
                                                        nx_path[1:]))
        nx_search_ms = bench(nx_search, nx_reps)

        # --- nano-astar
        astar(grid, start, goal)  # warmup
        astar(grid, start, goal)
        our_ms = bench(lambda: astar(grid, start, goal), our_reps)
        _, our_cost = astar(grid, start, goal)

        match = "yes" if abs(our_cost - nx_cost) < 1e-6 else f"NO ({our_cost} vs {nx_cost})"
        rows_out.append(dict(
            size=size, seed=seed,
            ours=our_ms,
            nx_search=nx_search_ms,
            nx_total=nx_build_ms + nx_search_ms,
            nx_build=nx_build_ms,
            speedup_search=nx_search_ms / our_ms,
            speedup_total=(nx_build_ms + nx_search_ms) / our_ms,
            cost_match=match,
        ))
        print(f"[{size}x{size}] ours {our_ms:.2f} ms | nx search "
              f"{nx_search_ms:.1f} ms | nx build+search "
              f"{nx_build_ms + nx_search_ms:.1f} ms | cost match: {match}",
              flush=True)

    # --- bucket queue vs 4-ary heap on integer (4-connected) grids
    bq_rows = []
    for size in SIZES:
        rng = np.random.default_rng(1000 + size)
        while True:
            grid = (rng.random((size, size)) < DENSITY).astype(np.uint8)
            start, goal = (0, 0), (size - 1, size - 1)
            grid[start] = 0
            grid[goal] = 0
            probe = _core.astar(grid, start, goal, "manhattan", False, False, False)
            if probe is not None:
                break
        reps = REPS[size][1]
        _core.astar(grid, start, goal, "manhattan", False, False, False)  # warm
        _core.astar(grid, start, goal, "manhattan", False, False, True)   # warm
        bq = bench(lambda: _core.astar(grid, start, goal, "manhattan",
                                       False, False, False), reps)
        hp = bench(lambda: _core.astar(grid, start, goal, "manhattan",
                                       False, False, True), reps)
        assert _core.astar(grid, start, goal, "manhattan", False, False, False)[1] == \
               _core.astar(grid, start, goal, "manhattan", False, False, True)[1]
        bq_rows.append((size, bq, hp, hp / bq))
        print(f"[bucket vs heap {size}x{size}] bucket {bq:.2f} ms | "
              f"heap {hp:.2f} ms | heap/bucket {hp / bq:.2f}x", flush=True)

    # --- write BENCH.md
    import nano_astar
    env = (f"Python {platform.python_version()}, networkx {nx.__version__}, "
           f"numpy {np.__version__}, nano-astar {nano_astar.__version__}, "
           f"MSVC 19.51 (cl /O2), {platform.platform()}")
    lines = [
        "# BENCH.md — nano-astar vs networkx",
        "",
        f"Environment: {env}",
        "",
        "Random grids, 30% obstacles, 8-connected moves (sqrt(2) diagonals, no",
        "corner cutting), octile heuristic on both sides. Median wall times;",
        "both sides warmed up. networkx build uses the fast vectorized",
        "construction in `tests/bench_vs_networkx.py` (same adjacency rules).",
        "",
        "| grid | seed | nano-astar (ms) | networkx search-only (ms) | networkx build+search (ms) | speedup (search only) | speedup (incl. build) | cost match |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows_out:
        lines.append(
            f"| {r['size']}x{r['size']} | {r['seed']} | {r['ours']:.2f} | "
            f"{r['nx_search']:.1f} | {r['nx_total']:.1f} | "
            f"{r['speedup_search']:.0f}x | {r['speedup_total']:.0f}x | "
            f"{r['cost_match']} |")
    lines += [
        "",
        "## Bucket queue vs 4-ary heap (integer 4-connected grids, manhattan)",
        "",
        "| grid | bucket queue (ms) | 4-ary heap (ms) | heap/bucket |",
        "|---|---|---|---|",
    ]
    for size, bq, hp, ratio in bq_rows:
        lines.append(f"| {size}x{size} | {bq:.2f} | {hp:.2f} | {ratio:.2f}x |")
    lines += [
        "",
        "Reproduce: `python tests/bench_vs_networkx.py`",
        "",
    ]
    out = REPO_ROOT / "BENCH.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {out}")

    # machine-readable copy for tools/make_bench_plot.py
    import json
    (REPO_ROOT / "docs" ).mkdir(exist_ok=True)
    (REPO_ROOT / "docs" / "bench_results.json").write_text(json.dumps({
        "env": env,
        "main": rows_out,
        "bucket_vs_heap": [
            {"size": s, "bucket": b, "heap": h} for s, b, h, _ in bq_rows],
    }, indent=2), encoding="utf-8")
    print("Wrote docs/bench_results.json")


if __name__ == "__main__":
    main()
